config/routes.rb
Rails.application.routes.draw do

  root "students#index"

  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	validates :language, acceptance: true
	validates :gender, acceptance: true
	has_one_attached :avatar
	before_save do
		self.language.gsub!(/[\[\]\"]/, "") if attribute_present?("language")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all.order(created_at: :desc)
  end

  def show
    @student = Student.find(params[:id])
  end 

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
      respond_to do |format|
        if @student.save
          format.js
        else
          render :new
        end
      end
  end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update

    @student = Student.find_by(id: params[:id])
    # @student.update(avatar: params[:file])
    @student.update(student_params)
      respond_to do |format|
        if @student.update(student_params)
          format.js
        else 
          format.js
        end
      end
  end
  def destroy
    @student = Student.find_by(id: params[:format])
  end


  private
  def student_params

    if params[:student]
    params.require(:student).permit(:name, :gender, :dob, :city, :avatar, language:[])
    else
      params.permit(:avatar)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
	def checked(area)
		@student.language.nil? ? false : @student.language.match(area)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oakacademy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<center><h1>Student Form</h1></center>
<div>
	<center style="background-color: #F9F9F9; width: 500px; margin-left: 200px;">
		<%= form_for(student,:html => {:id => "update_form"}, remote: true) do |s| %>
      		<div class="modal-body">
				<div class="avatar">
				<%= s.label "Image"%>
				<%= s.file_field :avatar, id:"avatar", onchange: "uploadimage()"%>
				</div>
				<div style="margin-top: 10px; margin-bottom: 10px;">
					<%= s.label :name %>
					<%= s.text_field :name %><br>
				</div>
				<div style="margin-top: 10px; margin-bottom: 10px;">
					<%= s.label :gender %><br>
					<%= s.radio_button :gender, "Male"%>MALE
					<%= s.radio_button :gender, "female" %>FEMALE<br>		
				</div>
				<div style="margin-top: 10px; margin-bottom: 10px;"> 
					<%= s.label :dob %>
					<%#= s.date_field :dob %><br>
				</div>
				<div style="margin-top: 10px; margin-bottom: 10px;">
					<%= s.label :city %>
					<%= s.select(:city, [['Indore', 1], ['Bhopal', 2],['Ujjain', 1], ['Omkareshwar', 1]]) %><br>
				</div>
				<div style="margin-top: 10px; margin-bottom: 10px;">
					<%= s.label :language %>
					<%= label_tag "Language", "English"%>
					<%= check_box_tag "student[language][]", "English", checked("English"), id: "language"%><br>
					<%= label_tag "Language", "Hindi"%>
					<%= check_box_tag "student[language][]", "Hindi", checked("English"),id: "language"%><br>
					<%= label_tag "Language", "Marathi"%>
					<%= check_box_tag "student[language][]", "marathi", checked("English"),id: "language"%><br>
				</div>
			</div>
			<div class="modal-footer">
  	  			<button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
				<%= s.submit "Submit Form", class:"btn btn-primary" %>
   			</div>
    	<% end %>
	</center>
</div>

app/views/students/_student.html.erb
 <div id="student_<%= student.id %>">
 Name: 
  <a href="<%= student_path(student) %>"><%= student.name %></a><hr>
 </div>

app/views/students/create.js.erb
$("#all-students").prepend("<%= escape_javascript render('student', student: @student)%>");
$(".close-modal").click();

app/views/students/edit.js.erb
$('#EditStudentForm').html("<%= escape_javascript render('form', student: @student)%>")

app/views/students/index.html.erb
<h1>Students </h1>

<div id="all-students">
  <% @students.each do |st| %>
  <%= render 'student', student: st%>
  <% end %> 
</div>

<%= link_to "New Student", new_student_path, class: "btn btn-primary",data: { bs_target: "#NewStudentForm", bs_toggle: "modal", remote: true } %>
<!-- Modal -->
<div class="modal fade" id="NewStudentForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="NewStudentFormLabel">New Student Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="NewStudentForm"> 

      </div>
    </div>
  </div>
</div>
 

app/views/students/new.js.erb
$("#NewStudentForm").html("<%= escape_javascript render('form', student: @student)%>");

app/views/students/show.html.erb
<div id="student_image">
	<% if @student.avatar.present?%>
	<div> Photo: <%= image_tag @student.avatar %></div>
	<% end %>
	<h1>Student <%=@student.id%> detail</h1>
	<div>Name: <%= @student.name %></div>
	<div>Gender: <%= @student.gender %></div>
	<div>Date of Birth: <%= @student.dob %></div>
	<div>City: <%= @student.city %></div>
	<div>Language: <%= @student.language %></div>
	<div><%= link_to "Delete", students_path, method: :delete%></div>


<%= link_to "Edit Student", edit_student_path, class: "btn btn-primary",data: { bs_target: "#EditStudentForm", bs_toggle: "modal", remote: true } %>
<!-- Modal -->
<div class="modal fade" id="EditStudentForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="EditStudentFormLabel">Edit Student Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    	<div id="EditStudentForm"> 

      </div>
    </div>
  </div>
</div>
</div>

<script>
function uploadimage(){
    var formData = new FormData();
        var url = $('#update_form').attr("action");
        var fileimage = $('#avatar')[0].files;
        formData.append("avatar", fileimage[0]);
         $.ajax({
            type: "PATCH",
            url: url,
            data: formData,
            processData: false,
            contentType: false,
        });
     }

</script>

app/views/students/update.js.erb
$(".close-modal").click();
$("#student_image").load("#student_image > *");